const UPDATEFACEDETECTED = "UPDATEFACEDETECTED"
const UPDATEYESDETECTED = "UPDATEYESDETECTED"
const UPDATENUMOFFACES = "UPDATENUMOFFACES"
const CHANGETHEME = "CHANGETHEME"
const SETUSER = "SETUSER"
const SETUSERPHOTO = "SETUSERPHOTO"

export {
    UPDATEFACEDETECTED,
    UPDATENUMOFFACES,
    UPDATEYESDETECTED,
    CHANGETHEME,
    SETUSER,
    SETUSERPHOTO
}