const UPDATEFACEDETECTED = "UPDATEFACEDETECTED"
const UPDATEYESDETECTED = "UPDATEYESDETECTED"
const UPDATENUMOFFACES = "UPDATENUMOFFACES"

export {
    UPDATEFACEDETECTED,
    UPDATENUMOFFACES,
    UPDATEYESDETECTED
}