const UPDATEFACEDETECTED = "UPDATEFACEDETECTED"
const UPDATEYESDETECTED = "UPDATEYESDETECTED"
const UPDATENUMOFFACES = "UPDATENUMOFFACES"
const CHANGETHEME = "CHANGETHEME"

export {
    UPDATEFACEDETECTED,
    UPDATENUMOFFACES,
    UPDATEYESDETECTED,
    CHANGETHEME
}